#print(10/0)

# try:
#     print(10/0)
# except ZeroDivisionError:
#     print("You cannot divide by zero")

# try:
#     print(10/40)
# except Exception as e:
#     print("Exception:",e)
#
# finally:
#     print("Finally")

# def add(x,y):
#     if y==0:
#         raise Exception('y cannot be zero')
#         # raise ZeroDivisionError('y cannot be zero') #can use instead of Exception
#
#     return x+y
#
# try:
#     print(add(10,70))
# except ZeroDivisionError as e:
#     print('Exception:',e)


